[changelog]
commit_parsers = [
    { message = ".*release.*", skip = true },
    { message = "^chore: release", skip = true },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^Merge pull request", skip = true },
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^doc", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore", group = "Miscellaneous Tasks" },
    { message = "^.*", group = "Other" },
]
